### ISSUE TITLE
Sessions hangs on broker service after scaling  -- 4-WVD-scaling-script

### ISSUE THREAD

**Issue by larshobiasen** [Azure/RDS-Templates#273] opened 2019-11-26 20:45 UTC
Hi,
we are using the WVD scaling script, but have a one problem.

When we are out of Peak hours we shutdown 5 out of 6 Win10 servers with the scaling script.

Some users report that they cant connect, and when i ran the "Get-RDSuserSessions" i can see some users with session pointing to the servers in shutdown state.

The "Invoke-RdsUserSessionLogoff" cant kill the sessions i the azure broker service - the only way to clear the "ghost" users from the azure broker service is to start the RDS servers, and the close them again.

then the "Get-RDSuserSessions" only display active sessions - and all users can the connect without problems.

Any suggistions to fix this problem?

Lars

**Comment by urighi** [comment] 2019-11-28 05:59
The script needs another check before shutting down hosts to make sure that no sessions for that host exist. I modified the script we use for that, adding the code below before the shutdown operations. To be honest, I'm writing a new from scratch because this one offered by MS has too many bugs and questionable coding decisions.

```
            # Re-check number of sessions
            try {
              $HostPoolUserSessions = Get-RdsUserSession -TenantName $TenantName -HostPoolName $HostpoolName
            }
            catch {
              Write-Log 1 "Failed to retrieve list of user sessions in hostPool: $($HostpoolName) with error: $($_.exception.message)" "Info"
              exit
            }

            foreach ($Session in $HostPoolUserSessions) {
              if ($Session.SessionHostName -eq $SessionHost) {
                Write-Log 1 "Sessions found in $($Session.SessionHostName). Script will exit and wait for next round." "Info"
                exit
              }
            }
```

**Comment by viswanadham-k** [comment] 2020-03-05 08:30
Hi @larshobiasen 

Can you please access the below link and configure the latest version of WVD Scaling tool it is recommended by Microsoft. This version have your issue fix.

https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script

Let us know if you are still facing issues.

Thanks,

**Comment by ChristianMontoya** [comment] 2020-03-08 21:31
As @viswanadham-k mentioned, please try the new script that uses logic apps and is fully described here in the public documentation: [Set up scaling script](https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script).

Closing this out. Please create a new issue if scenario reproduces.

**Closed by ChristianMontoya** 2020-03-08 21:31 UTC
Labels: 4-WVD-scaling-script, feature
