### ISSUE TITLE
New-AzResourceGroupDeployment : A parameter cannot be found that matches parameter name 'logicAppName'

### ISSUE THREAD

**Issue by Casey-Rickwood** [Azure/RDS-Templates#615] opened 2021-03-30 05:25 UTC
I've just started seeing the error message **"New-AzResourceGroupDeployment : A parameter cannot be found that matches parameter name 'logicAppName'."** within the CreateOrUpdateAzLogicApp.ps1file. It has been working up to this point.

I have also been using an Azure Powershell Task with the Latest PS version within an Azure DevOps Release Pipeline

**Comment by Dacuna16** [comment] 2021-04-28 20:52
> I've just started seeing the error message **"New-AzResourceGroupDeployment : A parameter cannot be found that matches parameter name 'logicAppName'."** within the CreateOrUpdateAzLogicApp.ps1file. It has been working up to this point.
> 
> I have also been using an Azure Powershell Task with the Latest PS version within an Azure DevOps Release Pipeline

I am having the same issue myself

**Comment by nakranimohit0** [comment] 2021-05-27 20:35
@Dacuna16 @Casey-Rickwood are you still seeing this issue ? Is this happening just on Azure DevOps or local powershell as well ? Can you share the PS environment details, https://github.com/Azure/RDS-Templates/issues/613#issuecomment-804444178

**Comment by FFantasma** [comment] 2021-06-01 20:36
I have this problem in PowerShell Local. I connect in the Client's environment, I run all the script, but when I get to the line to create the LogicApp, the error appears.

my environment 
![image](https://user-images.githubusercontent.com/19576265/120386821-82181f00-c2ff-11eb-877c-852131c0e3ee.png)

Error
![image](https://user-images.githubusercontent.com/19576265/120387067-d1f6e600-c2ff-11eb-93a6-323671e5bad3.png)

**Comment by nakranimohit0** [comment] 2021-07-26 20:57
Closing this out as there is no update from @Dacuna16 @Casey-Rickwood on the original issue. I'm unable to reproduce the issue on PowerShell 5. I simply don't have enough info to troubleshoot this further. Feel free to re-open this when you get back to me with more info about your PowerShell environment.

@FFantasma your issue seems to be different and same as #627 . which is where I'll address the issue

**Closed by nakranimohit0** 2021-07-26 20:57 UTC
Labels: 4-WVD-scaling-tool
