### ISSUE TITLE
4-WVD-scaling-tool - Add MinimumNumberOfRDSH for Peak hours

### ISSUE THREAD

**Issue by jbargallo** [Azure/RDS-Templates#554] opened 2020-09-25 11:28 UTC
As we only need VMs running during business hours, we set MinimumNumberOfRDSH to 0 in order to shut all of them down by night. The result is that no VM is ever turned on again. We thought that when peak time comes the script would start at least one machine but turns out it doesn’t do that, because it just estimates that 0 current sessions are well OK below the user/core threshold.

This leaves us needing complementary scripts just to manually start 1 machine to serve the initial demand at the beginning of business hours.

So we kindly ask for an optional new parameter MinimumNumberOfRDSHDuringPeakHours parameter or some equivalent mechanism, thanks!

**Comment by nakranimohit0** [comment] 2020-09-28 19:44
Closing this as duplicate of #520

**Closed by nakranimohit0** 2020-09-28 19:44 UTC
Labels: 4-WVD-scaling-tool

**Comment by jbargallo** [comment] 2020-09-28 20:23
Hi @nakranimohit0, I am not sure my request is exactly a duplicate of #520 (which I had already read first before opening mine), this is a slightly different issue here, the current script does not handle well an initial scenario of 0 VMs running, but thanks anyway.
