### ISSUE TITLE
Not  able to create WVD 

### ISSUE THREAD

**Issue by HimanshuMamodiya** [Azure/RDS-Templates#504] opened 2020-06-07 08:48 UTC
Hi ,

I am trying to create WVD using Azure Portal (used Spring 2020 way). But while creating WVD , I am getting below error: 

I have created users in Azure Active directory with Global Administrator and tenant creator role.
And using Azure AADDS .

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'joindomain'. Error message: \\\"Exception(s) occured while joining Domain 'himanshumamodiya6outlook.onmicrosoft.com'\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/vmextensionwindowstroubleshoot \"\r\n }\r\n ]\r\n }\r\n}"}]}

Please help me out how to resolve it,

**Comment by nakranimohit0** [comment] 2020-06-07 23:30
This is an issue with domain join which we don't have much control over as we are just calling the extension using the ARM. Although this is using spring update 2020, closing this as a duplicate of #434 . Please see https://aka.ms/vmextensionwindowstroubleshoot for more info on troubleshooting as mentioned by the error itself.

@datr93 FYI

**Closed by nakranimohit0** 2020-06-07 23:30 UTC
