### ISSUE TITLE
Updating a hostpool based on a managed image throws an error

### ISSUE THREAD

**Issue by TVDKoni** [Azure/RDS-Templates#223] opened 2019-08-27 22:05 UTC
I have an existing host pool created based on a managed image with the rdshCustomImageSourceName parameter.

Now I have a new managed image and like to update this existing host pool with this new managed image.

The deployment shows following error:
New-AzResourceGroupDeployment : 23:57:21 - Resource Microsoft.Compute/virtualMachines 'ssvtinfwvd51-0' failed with 
message '{
  "error": {
    "code": "PropertyChangeNotAllowed",
    "message": "Changing property 'imageReference.id' is not allowed.",
    "target": "imageReference.id"
  }
}'
At C:\Users\konrad.br 
(F921DD46)\Desktop\AzureConfiguration\setup\azure\wvd\Admin\Test\ssvtinfhpol001\deploy.ps1:123 char:5
+     New-AzResourceGroupDeployment -ResourceGroupName $ResourceGroupNa ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroup 
   DeploymentCmdlet

Can one explain me the right procedure to update such a host pool?

**Comment by rooso** [comment] 2019-12-05 21:06
Struggling with the same problem - don't know if I'm doing any wrong.

**Comment by Digiroka** [comment] 2020-01-06 17:06
Same issue when deploying the 'Update existing WVD host pool' template from Github.
If I rebuild the pool with the same image name, it works. If I rebuild the pool with a different image name, it fails with "Changing property 'imageReference.id' is not allowed."
Is this a supported process?

**Comment by stevenzelenko** [comment] 2020-01-09 02:58
Having the same exact issue when trying to add more host pools to a deployment.  I'm really at a loss for words as to how complicated this is for something that seems so simple.  The account I'm using has MFA disabled, a global admin, and is an RDS Owner.

**Comment by Digiroka** [comment] 2020-01-14 16:45
@ChristianMontoya - Can you let us know if this should work currently, if there is a bug to be fixed, or if the function will not be supported? Thanks.

**Comment by ChristianMontoya** [comment] 2020-01-14 16:58
@Digiroka  / @stevenzelenko / @TVDKoni : Let me take a look. I'm not immediately sure why you would be receiving that error.

**Comment by ChristianMontoya** [comment] 2020-01-14 17:50
@Digiroka / @stevenzelenko / @TVDKoni : Are any of you able to provide a sample Parameter list ? Anonymized is totally fine, just hoping to see the list for any specific indicators.

**Comment by Digiroka** [comment] 2020-01-14 18:01
Hi Christian, thanks for looking at this. My parameters for the deployment error below. 

`{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "vmImageVhdUri": {
            "value": ""
        },
        "storageAccountResourceGroupName": {
            "value": ""
        },
        "rdshGalleryImageSKU": {
            "value": "Windows-10-Enterprise-multi-session"
        },
        "rdshPrefix": {
            "value": "<REMOVED>"
        },
        "rdshNumberOfInstances": {
            "value": 1
        },
        "rdshVMDiskType": {
            "value": "Premium_LRS"
        },
        "rdshVmSize": {
            "value": "Standard_B2s"
        },
        "enableAcceleratedNetworking": {
            "value": false
        },
        "existingDomainusername": {
            "value": "<REMOVED>"
        },
        "existingDomainPassword": {
            "value": null
        },
        "vhds": {
            "value": "vhds/<REMOVED>"
        },
        "subnet-id": {
            "value": "/subscriptions/<REMOVED>"
        },
        "rdshImageSourceResourceGroup": {
            "value": "<REMOVED>"
        },
        "rdshImageSourceName": {
            "value": "WVD-MASTER-IMG-060120"
        },
        "location": {
            "value": "northeurope"
        }
    }
}`

**Comment by TVDKoni** [comment] 2020-01-14 18:02
Dear Christian
1. Deploy a hostpool based on an image with https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/Create%20and%20provision%20WVD%20host%20pool
2. Try to update that hostpool with a new image with https://github.com/Azure/RDS-Templates/tree/master/wvd-templates/Update%20existing%20WVD%20host%20pool
Thats all

**Comment by ChristianMontoya** [comment] 2020-01-23 23:38
@TVDKoni : Been a bit busy here, will try to look at this tomorrow or early next week. My initial thought is this is "by design" since the ARM template sees that the "-0" or other VM was already created but verifies some of the VM properties. Since the image name changed, this might be the cause of the error, but there is nothing else we could do to change how ARM evaluates the template.

**Comment by stevenzelenko** [comment] 2020-01-23 23:47
@ChristianMontoya the odd thing is that the VMs do get created with the correct sku, it just doesn’t install extensions or join to the domain.

**Comment by Monual** [comment] 2020-03-05 15:36
I wanted to leave a "me too" on this issue.  We also use custom managed images, and we too encounter this exact same issue when trying to update a host pool.  Right now we get around it by completely destroying the host pool and redeploying it with the updated image, but this is obviously far from ideal.  It would be nice if we could get this ARM template to work with custom images.

**Comment by richyla** [comment] 2020-03-14 22:13
As above facing same issue with managed images.  Is their use not recommended with WVD hostpool vms?

**Comment by nakranimohit0** [comment] 2020-03-19 02:02
@All

Does this error occur assuming there already exists a host pool of a VM say 'vm-0' with a managed custom image 'img-name' and then update this same host pool with a new VM 'new-vm-0' with a new managed custom image 'new-img-name' ?

**Comment by rooso** [comment] 2020-03-19 08:01
@nakranimohit0 in my case, the error only appears when the custom image name is different than the old one (like if i put versions in image name). There is no need to rename the vm's on my side.

**Comment by nakranimohit0** [comment] 2020-03-19 12:34
@rooso 
Then in your case, in order to use the update template, the new VM names MUST be unique (in that resource group). This is not an option. It is a requirement. With same VM name that is already existing, template will not change anything in azure.

We understand that this is a very common misunderstanding and we are working on improving the documentation and error logging on this matter.

**Comment by rooso** [comment] 2020-03-19 12:45
@nakranimohit0 Okey, thanks for clarification. But two days ago I used the update arm template with the same custom image name and aswell the same VM name. I just changed the vm size and the humbers of session hosts. No issues, old vm's got deleted and then the new one's were successfully built. The only thing was, that there was no 15 minutes counter and a message like it should be with my config. But anyway - I'll give it a try with a new vm name (might versioning them as well, could be useful). Thank you!

**Comment by nakranimohit0** [comment] 2020-03-19 13:03
@rooso 

It is very important to understand how these templates work. If a resource that the template is trying to create already exists, it will not do anything and will move on to the next one. In your test few days ago, the old VMs were not deleted, they were just ignored by the template and that is why there is no message on those old VMs because template thinks these are the new ones that it created. In addition to that, since you increased the number off VMs, template also created new additional VMs that didn't already exist in that resource group. After all this is done, it deletes any VMs that are not supposed to be part of this host pool and in your case, this list is empty.

**Comment by nakranimohit0** [comment] 2020-03-22 17:30
@TVDKoni 
Are you still running into this issue ? If not, can we close this one out ?

**Comment by smdhuri** [comment] 2020-03-24 22:51
Facing same issue while updating new image for existing HostPool.

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n \"error\": {\r\n \"code\": \"PropertyChangeNotAllowed\",\r\n \"message\": \"Changing property 'imageReference.id' is not allowed.\",\r\n \"target\": \"imageReference.id\"\r\n }\r\n}"},{"code":"Conflict","message":"{\r\n \"error\": {\r\n \"code\": \"PropertyChangeNotAllowed\",\r\n \"message\": \"Changing property 'imageReference.id' is not allowed.\",\r\n \"target\": \"imageReference.id\"\r\n }\r\n}"},

**Comment by nakranimohit0** [comment] 2020-03-24 22:54
@smdhuri 
Are you sure you are updating the existing host pool with a new image and a new VM name prefix ?

**Comment by smdhuri** [comment] 2020-03-25 11:38
New image with existing VM name prefix

**Comment by nakranimohit0** [comment] 2020-03-25 13:05
@smdhuri 
That's an invalid use of the template. Please see all of my comments above.

**Comment by nakranimohit0** [comment] 2020-04-28 19:07
Updating the existing VMs (same VM prefix name) with the new image is not supported right now. The workaround is to use the update templates to update the existing host pool with a different VM prefix name with the new image. This will create new VMs and remove old VMs from the host pool.

Closing this out now.

**Closed by nakranimohit0** 2020-04-28 19:07 UTC
Labels: 2-Update-existing-WVD-host-pool

**Comment by jflieben** [comment] 2021-01-21 10:41
Ran into this issue as well, hoped to fix it by using a reference, but that isn't allowed to the same resource. So I decided to add a parameter :

`    "existingNumberOfInstances":{
      "type": "int",
      "metadata": {
        "description": "Number of session hosts already present in the hostpool"
      },
      "defaultValue": 0
    },`

Then in the VM reference:
`            "storageProfile": {
                "imageReference": "[if(less(add(copyindex(), 0),parameters('existingNumberOfInstances')),json('null'),variables('imageReference'))]",
                "osDisk": {
                    "createOption": "FromImage",
                    "managedDisk": {
                        "storageAccountType": "[parameters('vmDiskType')]"
                    }
                }
            }`

This works fine, but obviously requires my devops pipeline to first count the existing VM instances. ARM should have some way to count/list/reference existing resources at deployment time.

**Comment by faizan002** [comment] 2021-01-29 12:46
I totally misunderstood how ARM templates are supposed to work, before I came to this thread. WTH, I change the image, since there were some minor updates and tried to deploy a simple VM (same name offcource) and it is not allowed. So, there is nothing called Redeployment of existing resource.

**Comment by jflieben** [comment] 2021-02-01 15:20
> I totally misunderstood how ARM templates are supposed to work, before I came to this thread. WTH, I change the image, since there were some minor updates and tried to deploy a simple VM (same name offcource) and it is not allowed. So, there is nothing called Redeployment of existing resource.

You did not misunderstand. However, several of Msft's dev teams don't write their components in such a way that they are idempotent or immediately mutable. 

In other words; yes, ARM is supposed to manage initial and subsequent delta deployments, but not all azure resources fully support it.

You can fix that by making complexer templates, multiple templates (nested or not) or powershell scripts before/after the deployment.

**Comment by jflieben** [comment] 2021-02-25 10:01
> I totally misunderstood how ARM templates are supposed to work, before I came to this thread. WTH, I change the image, since there were some minor updates and tried to deploy a simple VM (same name offcource) and it is not allowed. So, there is nothing called Redeployment of existing resource.

Here's an example of how we fixed this: https://gitlab.com/Lieben/assortedFunctions/-/blob/master/ARM%20templates/wvdDynamicHostpool.json
This one does allow delta deployments, but you'll have to supply the existing host count and/or disk list depending on the situation, see comments.
