### ISSUE TITLE
Issue: CreateOrUpdateAzAutoAccount.ps1 script output empty Webhook URI

### ISSUE THREAD

**Issue by KazTamai** [Azure/RDS-Templates#613] opened 2021-03-22 12:51 UTC
Webhook URI is empty after executing CreateOrUpdateAzAutoAccount.ps1. We should get Webhook URI after executing this PowerShell file but we can't get the expected result.

We just followed the document until step 4 on "Create or update an Azure Automation account" section then could not proceed because there is no webhook URI output.
https://docs.microsoft.com/en-us/azure/virtual-desktop/set-up-scaling-script

`Webhook URI:`

If we look at the code Line 317 on CreateOrUpdateAzAutoAccount.ps1, the Webhook URI is actually a property of $WebhookURI.
```PowerShell
Write-Output "Webhook URI: $($WebhookURI.value)"
```

On Line 229 and Line 235, $WebhookURI is actually the result of Get-AzAutomationVariable.

```PowerShell
$WebhookURI = Get-AzAutomationVariable -Name $WebhookURIAutoVarName -ResourceGroupName $ResourceGroupName -AutomationAccountName $AutomationAccountName -ErrorAction SilentlyContinue
```

We removed "-ErrorAction SilentlyContinue" to see the exact error message on execution and the output error was the following.
```PowerShell
Get-AzAutomationVariable: The variable was not found. VariableName WebhookURIARMBased.
Occurred at C:\Temp\CreateOrUpdateAzAutoAccount.ps1:229 Char:15
+ ... ebhookURI = Get-AzAutomationVariable -Name $WebhookURIAutoVarName -Re ...
+
    + CategoryInfo            : CloseError: (:) [Get-AzAutomationVariable], ResourceNotFoundException
    + FullyQualifiedErrorId: Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationVariable
```

**Comment by nakranimohit0** [comment] 2021-03-22 22:43
@KazTamai Not able to reproduce the issue in my environment below, what does your environment look like ?

```
PS > Get-Module


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.2.4      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}
Script     1.4.2      Az.Automation                       {Export-AzAutomationDscConfiguration, Export-AzAutomationDscNodeReportContent, Export-AzAutomationRunbook, Get-AzAutomationAccount...}
Script     2.3.0      Az.OperationalInsights              {Disable-AzOperationalInsightsIISLogCollection, Disable-AzOperationalInsightsLinuxCustomLogCollection, Disable-AzOperationalInsightsLinuxPerformanceCollection, Disable-AzOperationalInsightsLinuxSyslogCollection...}
Script     3.2.0      Az.Resources                        {Add-AzADGroupMember, Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzADAppCredential...}
Manifest   7.0.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty...}
Manifest   7.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSignature...}
Manifest   7.0.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Manifest   7.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, Enable-WSManCredSSP...}
Script     0.2.0      PowerShellEditorServices.Commands   {Clear-Host, ConvertFrom-ScriptExtent, ConvertTo-ScriptExtent, Find-Ast...}
Binary     0.2.0      PowerShellEditorServices.VSCode     {Close-VSCodeHtmlContentView, New-VSCodeHtmlContentView, Set-VSCodeHtmlContentView, Show-VSCodeHtmlContentView...}
Script     2.2.0      PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandler...}


PS > $PSVersionTable


Name                           Value
----                           -----
PSVersion                      5.1.19041.610
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.610
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3

```

**Comment by nakranimohit0** [comment] 2021-05-27 20:29
Closing it as there is no update

**Closed by nakranimohit0** 2021-05-27 20:29 UTC
Labels: 4-WVD-scaling-tool
