### ISSUE TITLE
Update image of  existing pool failed

### ISSUE THREAD

**Issue by Chai-NED** [Azure/RDS-Templates#446] opened 2020-04-24 18:18 UTC
I deployed this https://github.com/Azure/RDS-Templates/blob/master/wvd-templates/Update%20existing%20WVD%20host%20pool/README.md to update the image of a host pool. DSC extension failed only on one of the new 4 host sessions. Does anyone have an idea why?

Here is the error:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'dscextension'. Error message: \\\"DSC Configuration '**RegisterSessionHostAndCleanup**' completed with error(s). Following are the first few: PowerShell DSC resource MSFT_ScriptResource failed to execute Set-TargetResource functionality with error message: The received access token is not valid: at least one of the claims 'puid' or 'altsecid' or 'oid' should be present. If you are accessing as application please make sure service principal is properly created in the tenant. The SendConfigurationApply function did not succeed.\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot \"\r\n }\r\n ]\r\n }\r\n}"}]}

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/29571862/80243853-f4ff9280-8635-11ea-9cc1-38ec1fae77d6.png)

**Comment by nakranimohit0** [comment] 2020-04-28 19:39
@Chai-NED 
You need to give your service principal a "Contributor" role to the Azure subscription.

Closing this out as a duplicate of #321 
Please reopen if different

**Closed by nakranimohit0** 2020-04-28 19:39 UTC
Labels: 2-Update-existing-WVD-host-pool
