### ISSUE TITLE
Scaling tool - Off Peak - 1 Host shutdown

### ISSUE THREAD

**Issue by InfraVinny** [Azure/RDS-Templates#443] opened 2020-04-23 07:21 UTC
I'm having an issue where when the hours are off peak the tool is only shutting 1 host down.  This does eventually complete but it never moves on to other hosts.  When the script reruns 30 mins later it will attempt to shut the same machine down...

**Comment by bhavikbhakta** [comment] 2020-04-24 13:23
We ended up updating 613 and 1276 to use the **-and** operator instead of **-or**
`$SessionHost.Status -ne "NoHeartbeat" **-and** $SessionHost.Status -ne "Unavailable"`

There were issues with hosts being set to unavailable and weren't shutting down properly nor in the correct order.

**Comment by LeoLopezAtHL** [comment] 2020-04-24 14:21
Hi @InfraVinny ,
I see you were experiencing the same issue I did. Same solution. I submitted a case right after you.
I also noticed that the hosts that were left ON during Off Peak hours were left with the "AllowNewSession" set to "$False". No one was able to login in the morning until I manually changed it. Did you experience this issue as well?

**Comment by InfraVinny** [comment] 2020-04-24 14:25
So I updated to the latest sript and that seems to have resolved it.  The script still fails which i suspect is something timing out because it will evantually after 3 or 4 runs of the script scale them all back to where it should be.

**Comment by nicohendriks** [comment] 2020-04-29 12:51
We have the same problem, but maybe a stupid question how can we update the PowerShell Runbook script? We have run the following instruction: https://docs.microsoft.com/nl-nl/azure/virtual-desktop/set-up-scaling-script to setup the scaling tool!
But is it also possible to update only the PowerShell Runbook script?

**Comment by nicohendriks** [comment] 2020-04-29 13:17
> 
> 
> We have the same problem, but maybe a stupid question how can we update the PowerShell Runbook script? We have run the following instruction: https://docs.microsoft.com/nl-nl/azure/virtual-desktop/set-up-scaling-script to setup the scaling tool!
> But is it also possible to update only the PowerShell Runbook script?

I have find an instruction how to update: https://techcommunity.microsoft.com/t5/windows-virtual-desktop/how-to-update-wvd-scaling-tool-to-latest-published-version/m-p/1326581

**Comment by murray1472** [comment] 2020-04-30 11:40
We have the same problem and I can resolve the shutdown host error by switching the operator to -and at line 1276. The other issue is that remaining servers continue to be placed in to drain mode so no one can get a new session. Has anyone resolved this? It seems like section 1287 to 1291 is not calculating properly.

**Comment by LeoLopezAtHL** [comment] 2020-04-30 12:18
@murray1472 
I posted the issue and solution on issue #444 
I moved lines 1297 - 1299 up to line 1287 right before doing the drain. This is assuming you have it setup to not to drain hosts that have sessions on. Meaning this variable "$LimitSecondsToForceLogOffUser" is 0
This is the code of those 3 lines in case you your line numbers are not the same
if ($LimitSecondsToForceLogOffUser -eq 0) { 
continue
 }

**Comment by murray1472** [comment] 2020-05-01 16:08
@LeoLopezAtHL
Brill, thanks. moved it up and that is working. i'd prefer if we could put 3 of 4 in drain mode to drive any new sessions to single server that will remain on over night but this is definitely better than putting everything in drain mode and getting a phone call :)

**Comment by viswanadham-k** [comment] 2020-05-04 06:59
Hi All,
I am part of the scaling tool development.
Please let me know your availability time today then i will connect and assist you to resolve your issues. And share with me your mailing address then i will send a meeting invitation.

Thanks,

**Comment by cookiekaikai** [comment] 2020-05-05 19:24
> Hi All,
> I am part of the scaling tool development.
> Please let me know your availability time today then i will connect and assist you to resolve your issues. And share with me your mailing address then i will send a meeting invitation.
> 
> Thanks,

Can you help me as well?  My customer is having the same issue with the scaling down:

Processing hostpool KM-WVD-W10POOL01

Checking session host: AZUVDIW10-10.kindermorgan.com
  of sessions: 1 and status: Available

Checking session host: AZUVDIW10-0.kindermorgan.com
  of sessions: 2 and status: Available

Stopping Azure VM: AZUVDIW10-1 and waiting for it to complete ...

Azure VM has been stopped: AZUVDIW10-1 ...

HostpoolName: KM-WVD-W10POOL01, TotalRunningCores: 4 NumberOfRunningHosts: 1

**Comment by cookiekaikai** [comment] 2020-05-05 19:26
> Hi All,
> I am part of the scaling tool development.
> Please let me know your availability time today then i will connect and assist you to resolve your issues. And share with me your mailing address then i will send a meeting invitation.
> 
> Thanks,

Can you help me as well?  My customer is having the same issue:

**Comment by viswanadham-k** [comment] 2020-05-07 19:58
Hi All,
Hi @govjobss 
We have fixed issues which you have raised here in latest bits. So can you please follow the below steps and update the latest changes.

Below are the steps to update the Azure automation-based scaling tool located here to latest version
Access below link and copy the content of basicScale.ps1 code into a clipboard
https://raw.githubusercontent.com/Azure/RDS-Templates/master/wvd-templates/wvd-scaling-script/basicScale.ps1

Login to the Azure portal
In the Azure portal, select All services. In the list of resources, enter and select Automation Accounts.
On the Automation Accounts page, select the name of Automation account where you have the scaling tool hosted
Click on Runbooks under Process Automation section on the left hand side pane.
Click on PowerShell Runbook named “WVDAutoScaleRunbook”
Click on Edit from the top pane
Replace the existing code with one from Step 1
Click “Save” and “Publish”
New code will come into effect from next run of the runbook based on recurrence interval you have scheduled.

Please let me know if you are still facing issues. If it is working fine then close this issue.

Thanks

**Comment by nakranimohit0** [comment] 2020-05-31 17:36
Closing this out as there was no further update. Please open a new issue for session hosts left in drain mode, if it still exists.

**Comment by nakranimohit0** [comment] 2020-05-31 17:36
Original issue was also a duplicate of #461. Fixed in PR https://github.com/Azure/RDS-Templates/pull/467

**Closed by nakranimohit0** 2020-05-31 17:36 UTC
Labels: 4a-WVD-scaling-logicapps
