### ISSUE TITLE
ARM-wvd-templates/DSC/Functions.ps1 still using non-ARM powershell

### ISSUE THREAD

**Issue by erjosito** [Azure/RDS-Templates#583] opened 2020-12-08 09:26 UTC
If I read it correctly, the DSC code stored in https://github.com/Azure/RDS-Templates/blob/master/ARM-wvd-templates/DSC/Functions.ps1 still uses non-ARM powershell cmdlets such as Add-RdsAccount, Get-RdsContext or Add-RdsAppGroupUser.

Is there any plan to update it to use the newer ARM-WVD powershell commandlets? (https://github.com/fberson/wvd/blob/master/Add-WVDHostToHostpoolSpring.ps1 might be used as a reference)

**Comment by lintFan** [comment] 2020-12-12 03:21
Hi @erjosito, Functions.ps1 contains some code that is shared between the [WVD classic ARM templates](https://github.com/Azure/RDS-Templates/tree/master/wvd-templates) and [WVD non-classic ARM templates](https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates) however the functions that use the non-ARM cmdlets are only used by the WVD classic templates.

The file [ARM-wvd-templates/DSC/Functions.ps1](https://github.com/Azure/RDS-Templates/blob/master/ARM-wvd-templates/DSC/Functions.ps1) was a recently added duplicate of the original file [wvd-templates/DSC/Functions.ps1](https://github.com/Azure/RDS-Templates/blob/master/wvd-templates/DSC/Functions.ps1), I have just deleted ARM-wvd-templates/DSC/Functions.ps1 as it wasn't needed.

I have also added a readme to [ARM-wvd-templates/DSC](https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates/DSC) to explain what these files are used for.

I'll close this now but let me know if you have additional quesitons.

**Closed by lintFan** 2020-12-12 03:21 UTC
Labels: 1-Create-and-provision-host-pool-arm, 2-Update-existing-WVD-host-pool-arm

**Comment by erjosito** [comment] 2020-12-14 10:51
If you just removed the Functions.ps1 file, wouldnt the ARM templates under /ARM-wvd-templates/nestedtemplates be broken?

**Comment by lintFan** [comment] 2020-12-14 20:56
@erjosito no it won't break anything because Functions.ps1 is only referenced from the Azure Desired State code which is all contained in ARM-wvd-templates/DSC/Configuration.zip and Configuration.zip contains a copy of Functions.ps1 per the read me I added to [ARM-wvd-templates/DSC/](https://github.com/Azure/RDS-Templates/tree/master/ARM-wvd-templates/DSC).
